## **Data**

In [ ]:
import pandas as pd

df_target = pd.read_csv('.\\datas\\Summer-Olympic-medals-1976-to-2008.csv', encoding='cp1252')
df_target.head()

,City,Year,Sport,Discipline,Event,Athlete,Gender,Country_Code,Country,Event_gender,Medal
0,Montreal,1976.0,Aquatics,Diving,3m springboard,"KÖHLER, Christa",Women,GDR,East Germany,W,Silver
1,Montreal,1976.0,Aquatics,Diving,3m springboard,"KOSENKOV, Aleksandr",Men,URS,Soviet Union,M,Bronze
2,Montreal,1976.0,Aquatics,Diving,3m springboard,"BOGGS, Philip George",Men,USA,United States,M,Gold
3,Montreal,1976.0,Aquatics,Diving,3m springboard,"CAGNOTTO, Giorgio Franco",Men,ITA,Italy,M,Silver
4,Montreal,1976.0,Aquatics,Diving,10m platform,"WILSON, Deborah Keplar",Women,USA,United States,W,Bronze

In [2]:
df_target.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15433 entries, 0 to 15432
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   City          15316 non-null  object
 1   Year          15316 non-null  float64
 2   Sport         15316 non-null  object
 3   Discipline    15316 non-null  object
 4   Event         15316 non-null  object
 5   Athlete       15316 non-null  object
 6   Gender        15316 non-null  object
 7   Country_Code  15316 non-null  object
 8   Country       15316 non-null  object
 9   Event_gender  15316 non-null  object
 10  Medal         15316 non-null  object
dtypes: float64(1), object(10)
memory usage: 1.3+ MB

In [3]:
# 결측치 처리
df_target = df_target.dropna().reset_index(drop=True)
df_target.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15316 entries, 0 to 15315
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   City          15316 non-null  object
 1   Year          15316 non-null  float64
 2   Sport         15316 non-null  object
 3   Discipline    15316 non-null  object
 4   Event         15316 non-null  object
 5   Athlete       15316 non-null  object
 6   Gender        15316 non-null  object
 7   Country_Code  15316 non-null  object
 8   Country       15316 non-null  object
 9   Event_gender  15316 non-null  object
 10  Medal         15316 non-null  object
dtypes: float64(1), object(10)
memory usage: 1.3+ MB

In [4]:
# Year 컬럼 Data Type 변환
df_target['Year'] = df_target['Year'].astype(int)
df_target.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15316 entries, 0 to 15315
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   City          15316 non-null  object
 1   Year          15316 non-null  int32
 2   Sport         15316 non-null  object
 3   Discipline    15316 non-null  object
 4   Event         15316 non-null  object
 5   Athlete       15316 non-null  object
 6   Gender        15316 non-null  object
 7   Country_Code  15316 non-null  object
 8   Country       15316 non-null  object
 9   Event_gender  15316 non-null  object
 10  Medal         15316 non-null  object
dtypes: int32(1), object(10)
memory usage: 1.2+ MB

In [5]:
# 2008년 베이징 올림픽 양궁 종목 대한민국 금메달 리스트
df_target[df_target['Sport'] == 'Archery']['Discipline'].value_counts()

Discipline
Archery    162
Name: count, dtype: int64

In [6]:
tmp_df = df_target.copy()
df_archery = tmp_df[(tmp_df['City'] == 'Beijing') & (tmp_df['Year'] == 2008)]
df_archery = df_archery[(df_archery['Sport'] == 'Archery') & (df_archery['Medal'] == 'Gold')]
df_archery = df_archery[df_archery['Country_Code'] == 'KOR']
df_archery

,City,Year,Sport,Discipline,Event,Athlete,Gender,Country_Code,Country,Event_gender,Medal
13622,Beijing,2008,Archery,Archery,team (FITA Olympic round - 70m),"YUN, Ok-Hee",Women,KOR,"Korea, South",W,Gold
13636,Beijing,2008,Archery,Archery,team (FITA Olympic round - 70m),"JOO, Hyun-Jung",Women,KOR,"Korea, South",W,Gold
13637,Beijing,2008,Archery,Archery,team (FITA Olympic round - 70m),"LEE, Chang-Hwan",Men,KOR,"Korea, South",M,Gold
13639,Beijing,2008,Archery,Archery,team (FITA Olympic round - 70m),"IM, Dong-Hyun",Men,KOR,"Korea, South",M,Gold
13640,Beijing,2008,Archery,Archery,team (FITA Olympic round - 70m),"PARK, Kyung-Mo",Men,KOR,"Korea, South",M,Gold
13644,Beijing,2008,Archery,Archery,team (FITA Olympic round - 70m),"PARK, Sung-Hyun",Women,KOR,"Korea, South",W,Gold

In [7]:
# 대한민국 역대 (1976 ~ 2008) 하계 올림픽 메달 현황
tmp_df = df_target.copy()
display(tmp_df.info())

df_kor = tmp_df[tmp_df['Country_Code'] == 'KOR']
display(df_kor.info())

check_dup_cols = [col for col in df_kor.columns if col not in ['Athlete', 'Gender']]
df_kor = df_kor.drop_duplicates(subset=check_dup_cols)
display(df_kor.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15316 entries, 0 to 15315
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   City          15316 non-null  object
 1   Year          15316 non-null  int32
 2   Sport         15316 non-null  object
 3   Discipline    15316 non-null  object
 4   Event         15316 non-null  object
 5   Athlete       15316 non-null  object
 6   Gender        15316 non-null  object
 7   Country_Code  15316 non-null  object
 8   Country       15316 non-null  object
 9   Event_gender  15316 non-null  object
 10  Medal         15316 non-null  object
dtypes: int32(1), object(10)
memory usage: 1.2+ MB

None

<class 'pandas.core.frame.DataFrame'>
Index: 454 entries, 901 to 15308
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   City          454 non-null    object
 1   Year          454 non-null    int32
 2   Sport         454 non-null    object
 3   Discipline    454 non-null    object
 4   Event         454 non-null    object
 5   Athlete       454 non-null    object
 6   Gender        454 non-null    object
 7   Country_Code  454 non-null    object
 8   Country       454 non-null    object
 9   Event_gender  454 non-null    object
 10  Medal         454 non-null    object
dtypes: int32(1), object(10)
memory usage: 40.8+ KB

None

<class 'pandas.core.frame.DataFrame'>
Index: 202 entries, 901 to 15308
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   City          202 non-null    object
 1   Year          202 non-null    int32
 2   Sport         202 non-null    object
 3   Discipline    202 non-null    object
 4   Event         202 non-null    object
 5   Athlete       202 non-null    object
 6   Gender        202 non-null    object
 7   Country_Code  202 non-null    object
 8   Country       202 non-null    object
 9   Event_gender  202 non-null    object
 10  Medal         202 non-null    object
dtypes: int32(1), object(10)
memory usage: 18.1+ KB

None

In [ ]:
# Year과 Medal 컬럼으로 그루핑
grouped_df_kor = df_kor.groupby(['Year', 'Medal'])['City'].count().reset_index(name='City')
grouped_df_kor

    Year   Medal  City
0   1976  Bronze     4
1   1976    Gold     1
2   1976  Silver     1
3   1984  Bronze     7
4   1984    Gold     6
5   1984  Silver     6
6   1988  Bronze    11
7   1988    Gold    12
8   1988  Silver    10
9   1992  Bronze    11
10  1992    Gold    12
11  1992  Silver     5
12  1996  Bronze     5
13  1996    Gold     7
14  1996  Silver    15
15  2000  Bronze    10
16  2000    Gold     8
17  2000  Silver    10
18  2004  Bronze     9
19  2004    Gold     9
20  2004  Silver    12
21  2008  Bronze     8
22  2008    Gold    13
23  2008  Silver    10

In [ ]:
# 멀티 인덱스 테이블 생성
grouped_df_kor = grouped_df_kor.set_index(['Year', 'Medal'])
grouped_df_kor

             City
Year Medal
1976 Bronze     4
     Gold       1
     Silver     1
1984 Bronze     7
     Gold       6
     Silver     6
1988 Bronze    11
     Gold      12
     Silver    10
1992 Bronze    11
     Gold      12
     Silver     5
1996 Bronze     5
     Gold       7
     Silver    15
2000 Bronze    10
     Gold       8
     Silver    10
2004 Bronze     9
     Gold       9
     Silver    12
2008 Bronze     8
     Gold      13
     Silver    10

In [ ]:
# 정렬 (금, 은, 동)
sort_order = {'Gold': 0, 'Silver': 1, 'Bronze': 2}
sorted_df_kor = grouped_df_kor.sort_index(
    level=['Year', 'Medal'],
    ascending=[True, True],
    key=lambda x: x.map(sort_order) if x.name == 'Medal' else x
)
sorted_df_kor

             City
Year Medal
1976 Gold       1
     Silver     1
     Bronze     4
1984 Gold       6
     Silver     6
     Bronze     7
1988 Gold      12
     Silver    10
     Bronze    11
1992 Gold      12
     Silver     5
     Bronze    11
1996 Gold       7
     Silver    15
     Bronze     5
2000 Gold       8
     Silver    10
     Bronze    10
2004 Gold       9
     Silver    12
     Bronze     9
2008 Gold      13
     Silver    10
     Bronze     8

In [12]:
# 1996년 애틀랜타 올림픽 총 메달 개수 기준 상위 10개 국가
tmp_df = df_target.copy()
display(tmp_df.info())

tmp_df = tmp_df[tmp_df['City'] == 'Atlanta']

check_dup_cols = [col for col in tmp_df.columns if col not in ['Athlete', 'Gender']]
tmp_df = tmp_df.drop_duplicates(subset=check_dup_cols)
display(tmp_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15316 entries, 0 to 15315
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   City          15316 non-null  object
 1   Year          15316 non-null  int32
 2   Sport         15316 non-null  object
 3   Discipline    15316 non-null  object
 4   Event         15316 non-null  object
 5   Athlete       15316 non-null  object
 6   Gender        15316 non-null  object
 7   Country_Code  15316 non-null  object
 8   Country       15316 non-null  object
 9   Event_gender  15316 non-null  object
 10  Medal         15316 non-null  object
dtypes: int32(1), object(10)
memory usage: 1.2+ MB

None

<class 'pandas.core.frame.DataFrame'>
Index: 841 entries, 7402 to 9260
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   City          841 non-null    object
 1   Year          841 non-null    int32
 2   Sport         841 non-null    object
 3   Discipline    841 non-null    object
 4   Event         841 non-null    object
 5   Athlete       841 non-null    object
 6   Gender        841 non-null    object
 7   Country_Code  841 non-null    object
 8   Country       841 non-null    object
 9   Event_gender  841 non-null    object
 10  Medal         841 non-null    object
dtypes: int32(1), object(10)
memory usage: 75.6+ KB

None

In [ ]:
# 국가별 그루핑
grouped_df = tmp_df.groupby(['Country']).size().reset_index(name='Medal')
grouped_df.head()

     Country  Medal
0    Algeria      3
1  Argentina      3
2    Armenia      2
3  Australia     41
4    Austria      3

In [ ]:
# 정렬 후 상위 10개 국가 추출
df_rank_10 = grouped_df.sort_values(by='Medal', ascending=False).head(10)
df_rank_10

          Country  Medal
75  United States    101
24        Germany     65
58         Russia     63
13          China     50
3       Australia     41
22         France     37
33          Italy     35
39   Korea, South     27
16           Cuba     25
73        Ukraine     23

In [ ]:
# 1996년 애틀랜타 올림픽 금, 은, 동메달 개수 기준 상위 10개 국가
tmp_df = df_target.copy()
df_1996 = tmp_df[tmp_df['Year'] == 1996]

check_dup_cols = [col for col in df_1996.columns if col not in ['Athlete', 'Gender']]
df_1996 = df_1996.drop_duplicates(subset=check_dup_cols)
df_1996.info()

<class 'pandas.core.frame.DataFrame'>
Index: 841 entries, 7402 to 9260
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   City          841 non-null    object
 1   Year          841 non-null    int32
 2   Sport         841 non-null    object
 3   Discipline    841 non-null    object
 4   Event         841 non-null    object
 5   Athlete       841 non-null    object
 6   Gender        841 non-null    object
 7   Country_Code  841 non-null    object
 8   Country       841 non-null    object
 9   Event_gender  841 non-null    object
 10  Medal         841 non-null    object
dtypes: int32(1), object(10)
memory usage: 75.6+ KB

In [ ]:
# 금, 은, 동메달 one-hot encoding
df_1996['Gold'] = (df_1996['Medal'] == 'Gold').astype(int)
df_1996['Silver'] = (df_1996['Medal'] == 'Silver').astype(int)
df_1996['Bronze'] = (df_1996['Medal'] == 'Bronze').astype(int)
df_1996.head()

,City,Year,Sport,Discipline,Event,Athlete,Gender,Country_Code,Country,Event_gender,Medal,Gold,Silver,Bronze
7402,Atlanta,1996,Aquatics,Diving,3m springboard,"YU, Zhuocheng",Men,CHN,China,M,Silver,0,1,0
7403,Atlanta,1996,Aquatics,Diving,3m springboard,"XIONG, Ni",Men,CHN,China,M,Gold,1,0,0
7404,Atlanta,1996,Aquatics,Diving,10m platform,"HEMPEL, Jan",Men,GER,Germany,M,Silver,0,1,0
7405,Atlanta,1996,Aquatics,Diving,10m platform,"CLARK, Mary Ellen",Women,USA,United States,W,Bronze,0,0,1
7406,Atlanta,1996,Aquatics,Diving,3m springboard,"LASHKO, Irina",Women,RUS,Russia,W,Silver,0,1,0

In [ ]:
# 국가별 그루핑
grouped_df = df_1996.groupby(['Country'], as_index=False)[['Gold', 'Silver', 'Bronze']].sum()
grouped_df.head()

     Country  Gold  Silver  Bronze
0    Algeria     2       0       1
1  Argentina     0       2       1
2    Armenia     1       1       0
3  Australia     9       9      23
4    Austria     0       1       2

In [ ]:
# 정렬 후 상위 10개 추출
df_rank_10 = grouped_df.sort_values(by=['Gold', 'Silver', 'Bronze'],
                                    ascending=[False, False, False]).head(10)
df_rank_10

          Country  Gold  Silver  Bronze
75  United States    44      32      25
58         Russia    26      21      16
24        Germany    20      18      27
13          China    16      22      12
22         France    15       7      15
33          Italy    13      10      12
3       Australia     9       9      23
16           Cuba     9       8       8
73        Ukraine     9       2      12
39   Korea, South     7      15       5