In [3]:
# Raw Data Loading
import json

with open('C:\\education\\제로베이스\\[데이터 취업 스쿨] 강의 자료\\Part 7. Python 데이터 분석\\실습과제\\05. 전국 박물관 미술관 정보 표준 데이터 분석\\datas\\전국박물관미술관정보표준데이터.json', 'r', encoding='utf-8') as f:
    json_data = json.load(f)
json_data['fields'][:10]

[{'id': '시설명'},
 {'id': '박물관미술관구분'},
 {'id': '소재지도로명주소'},
 {'id': '소재지지번주소'},
 {'id': '위도'},
 {'id': '경도'},
 {'id': '운영기관전화번호'},
 {'id': '운영기관명'},
 {'id': '운영홈페이지'},
 {'id': '편의시설정보'}]

In [4]:
# json -> DataFrame 변환
import pandas as pd

df_target = pd.DataFrame(json_data['records'])
df_target.head(1)

,시설명,박물관미술관구분,소재지도로명주소,소재지지번주소,위도,경도,운영기관전화번호,운영기관명,운영홈페이지,편의시설정보,...,청소년관람료,어린이관람료,관람료기타정보,박물관미술관소개,교통안내정보,관리기관전화번호,관리기관명,데이터기준일자,제공기관코드,제공기관명
0,풀짚공예박물관,사립,경기도 광주시 오포읍 문형산길 76,,37.36419778,127.1651063,031-717-4538,풀짚공예박물관,,,...,1500,1500,특별전시입장료-일반(3000)+특별전시입장료-미취학(1500)+특별전시입장료-유치원...,,,031-717-4538,풀짚공예박물관,2022-06-16,1371000,문화체육관광부

In [5]:
df_target.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2117 entries, 0 to 2116
Data columns (total 26 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   시설명        2117 non-null   object
 1   박물관미술관구분   2117 non-null   object
 2   소재지도로명주소   2117 non-null   object
 3   소재지지번주소    2117 non-null   object
 4   위도         2117 non-null   object
 5   경도         2117 non-null   object
 6   운영기관전화번호   2117 non-null   object
 7   운영기관명      2117 non-null   object
 8   운영홈페이지     2117 non-null   object
 9   편의시설정보     2117 non-null   object
 10  평일관람시작시각   2117 non-null   object
 11  평일관람종료시각   2117 non-null   object
 12  공휴일관람시작시각  2117 non-null   object
 13  공휴일관람종료시각  2117 non-null   object
 14  휴관정보       2117 non-null   object
 15  어른관람료      2117 non-null   object
 16  청소년관람료     2117 non-null   object
 17  어린이관람료     2117 non-null   object
 18  관람료기타정보    2117 non-null   object
 19  박물관미술관소개   2117 non-null   object
 20  교통안내정보     2117 non-null   object
 21  관리기관전화번호   2117 non-null   object
 22  관리기관명      2117 non-null   object
 23  데이터기준일자    2117 non-null   object
 24  제공기관코드     2117 non-null   object
 25  제공기관명      2117 non-null   object
dtypes: object(26)
memory usage: 430.1+ KB

In [6]:
# json의 결측치는 ''로 저장되기 때문에
# DataFrame에서도 결측치로 나오지 않음
# ''값 결측치로 채우기
df_target = df_target.replace({"": pd.NA})
df_target.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2117 entries, 0 to 2116
Data columns (total 26 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   시설명        2117 non-null   object
 1   박물관미술관구분   2117 non-null   object
 2   소재지도로명주소   2117 non-null   object
 3   소재지지번주소    701 non-null    object
 4   위도         2117 non-null   object
 5   경도         2116 non-null   object
 6   운영기관전화번호   2117 non-null   object
 7   운영기관명      2117 non-null   object
 8   운영홈페이지     804 non-null    object
 9   편의시설정보     406 non-null    object
 10  평일관람시작시각   2117 non-null   object
 11  평일관람종료시각   2117 non-null   object
 12  공휴일관람시작시각  2117 non-null   object
 13  공휴일관람종료시각  2117 non-null   object
 14  휴관정보       2117 non-null   object
 15  어른관람료      2117 non-null   object
 16  청소년관람료     2117 non-null   object
 17  어린이관람료     2117 non-null   object
 18  관람료기타정보    726 non-null    object
 19  박물관미술관소개   561 non-null    object
 20  교통안내정보     417 non-null    object
 21  관리기관전화번호   2117 non-null   object
 22  관리기관명      2117 non-null   object
 23  데이터기준일자    2117 non-null   object
 24  제공기관코드     2117 non-null   object
 25  제공기관명      2117 non-null   object
dtypes: object(26)
memory usage: 430.1+ KB

In [8]:
# object로 저장되어 있는 수치형 데이터 int, float로 변환
type_int_col = ['어른관람료', '청소년관람료', '어린이관람료']
type_float_col = ['위도', '경도']

tmp_df = df_target.copy()
for col in type_int_col:
    tmp_df[col] = tmp_df[col].fillna(0).astype(int)

for col in type_float_col:
    tmp_df[col] = tmp_df[col].fillna(0).astype(float)

df_target = tmp_df.copy()
df_target.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2117 entries, 0 to 2116
Data columns (total 26 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   시설명        2117 non-null   object
 1   박물관미술관구분   2117 non-null   object
 2   소재지도로명주소   2117 non-null   object
 3   소재지지번주소    701 non-null    object
 4   위도         2117 non-null   float64
 5   경도         2117 non-null   float64
 6   운영기관전화번호   2117 non-null   object
 7   운영기관명      2117 non-null   object
 8   운영홈페이지     804 non-null    object
 9   편의시설정보     406 non-null    object
 10  평일관람시작시각   2117 non-null   object
 11  평일관람종료시각   2117 non-null   object
 12  공휴일관람시작시각  2117 non-null   object
 13  공휴일관람종료시각  2117 non-null   object
 14  휴관정보       2117 non-null   object
 15  어른관람료      2117 non-null   int32
 16  청소년관람료     2117 non-null   int32
 17  어린이관람료     2117 non-null   int32
 18  관람료기타정보    726 non-null    object
 19  박물관미술관소개   561 non-null    object
 20  교통안내정보     417 non-null    object
 21  관리기관전화번호   2117 non-null   object
 22  관리기관명      2117 non-null   object
 23  데이터기준일자    2117 non-null   object
 24  제공기관코드     2117 non-null   object
 25  제공기관명      2117 non-null   object
dtypes: float64(2), int32(3), object(21)
memory usage: 405.3+ KB

In [9]:
# 필요없는 컬럼 삭제
drop_cols = ['소재지지번주소', '위도', '경도', '운영기관전화번호','운영기관명', '운영홈페이지', '편의시설정보', '휴관정보', 
            '관람료기타정보', '박물관미술관소개', '교통안내정보', '관리기관전화번호', '관리기관명', '제공기관코드', '제공기관명']

df_target = df_target.drop(columns=drop_cols)
df_target.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2117 entries, 0 to 2116
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   시설명        2117 non-null   object
 1   박물관미술관구분   2117 non-null   object
 2   소재지도로명주소   2117 non-null   object
 3   평일관람시작시각   2117 non-null   object
 4   평일관람종료시각   2117 non-null   object
 5   공휴일관람시작시각  2117 non-null   object
 6   공휴일관람종료시각  2117 non-null   object
 7   어른관람료      2117 non-null   int32
 8   청소년관람료     2117 non-null   int32
 9   어린이관람료     2117 non-null   int32
 10  데이터기준일자    2117 non-null   object
dtypes: int32(3), object(8)
memory usage: 157.2+ KB

In [10]:
# 관람료가 10원 단위로 떨어지지 않는 데이터 이상치로 간주하고 삭제
# 또는 100000원 이상인 경우도 이상치로 간주하고 삭제
tmp_df = df_target.copy()
for col in type_int_col:
    tmp_df = tmp_df[(tmp_df[col] % 10 == 0) & (tmp_df[col] < 100000)]

df_target = tmp_df.copy()
df_target.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2111 entries, 0 to 2116
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   시설명        2111 non-null   object
 1   박물관미술관구분   2111 non-null   object
 2   소재지도로명주소   2111 non-null   object
 3   평일관람시작시각   2111 non-null   object
 4   평일관람종료시각   2111 non-null   object
 5   공휴일관람시작시각  2111 non-null   object
 6   공휴일관람종료시각  2111 non-null   object
 7   어른관람료      2111 non-null   int32
 8   청소년관람료     2111 non-null   int32
 9   어린이관람료     2111 non-null   int32
 10  데이터기준일자    2111 non-null   object
dtypes: int32(3), object(8)
memory usage: 173.2+ KB

In [11]:
# 휴관중이거나 중복된 박물관/미술관 삭제 (최신 데이터만 남기기)
tmp_df = df_target.copy()

tmp_df = tmp_df[~tmp_df['시설명'].str.contains('휴관')]

tmp_df = tmp_df.sort_values(by='데이터기준일자', ascending=False)
tmp_df['시설명'] = tmp_df['시설명'].str.replace(' ', '')
tmp_df = tmp_df.drop_duplicates(subset='시설명', keep='first')

tmp_df = tmp_df.sort_index()

df_target = tmp_df.copy()
df_target.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1361 entries, 0 to 2112
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   시설명        1361 non-null   object
 1   박물관미술관구분   1361 non-null   object
 2   소재지도로명주소   1361 non-null   object
 3   평일관람시작시각   1361 non-null   object
 4   평일관람종료시각   1361 non-null   object
 5   공휴일관람시작시각  1361 non-null   object
 6   공휴일관람종료시각  1361 non-null   object
 7   어른관람료      1361 non-null   int32
 8   청소년관람료     1361 non-null   int32
 9   어린이관람료     1361 non-null   int32
 10  데이터기준일자    1361 non-null   object
dtypes: int32(3), object(8)
memory usage: 111.6+ KB

In [ ]:
# 관람가능시간 컬럼 추가 (23시간 초과하는 경우 24시간으로 저장)
# 현재 아래 방법은 새벽에 관람을 종료하는 곳이 없기 때문에 문제없음
# 만약 있다면 음수가 나올 수 있으므로 추가적인 처리 필요
tmp_df = df_target.copy()

tmp_df['평일관람시작시간'] = tmp_df['평일관람시작시각'].str.split(':').str[0].astype(int)
tmp_df['평일관람시작분'] = tmp_df['평일관람시작시각'].str.split(':').str[1].astype(int)
tmp_df['평일관람종료시간'] = tmp_df['평일관람종료시각'].str.split(':').str[0].astype(int)
tmp_df['평일관람종료분'] = tmp_df['평일관람종료시각'].str.split(':').str[1].astype(int)

tmp_df['공휴일관람시작시간'] = tmp_df['공휴일관람시작시각'].str.split(':').str[0].astype(int)
tmp_df['공휴일관람시작분'] = tmp_df['공휴일관람시작시각'].str.split(':').str[1].astype(int)
tmp_df['공휴일관람종료시간'] = tmp_df['공휴일관람종료시각'].str.split(':').str[0].astype(int)
tmp_df['공휴일관람종료분'] = tmp_df['공휴일관람종료시각'].str.split(':').str[1].astype(int)

tmp_df['평일관람가능시간'] = (tmp_df['평일관람종료시간'] - tmp_df['평일관람시작시간']) + \
                            (tmp_df['평일관람종료분'] - tmp_df['평일관람시작분']) / 60
tmp_df['공휴일관람가능시간'] = (tmp_df['공휴일관람종료시간'] - tmp_df['공휴일관람시작시간']) + \
                            (tmp_df['공휴일관람종료분'] - tmp_df['공휴일관람시작분']) / 60

time_col = ['평일관람가능시간', '공휴일관람가능시간']
for col in time_col:
    tmp_df[col] = tmp_df[col].apply(lambda x: 24 if x > 23 else x)
    tmp_df[col] = tmp_df[col].round(2)

drop_col = ['평일관람시작시간', '평일관람시작분', '평일관람종료시간', '평일관람종료분',
            '공휴일관람시작시간', '공휴일관람시작분', '공휴일관람종료시간', '공휴일관람종료분']
tmp_df = tmp_df.drop(columns=drop_col)

df_target = tmp_df.copy()
df_target.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1361 entries, 0 to 2112
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   시설명        1361 non-null   object
 1   박물관미술관구분   1361 non-null   object
 2   소재지도로명주소   1361 non-null   object
 3   평일관람시작시각   1361 non-null   object
 4   평일관람종료시각   1361 non-null   object
 5   공휴일관람시작시각  1361 non-null   object
 6   공휴일관람종료시각  1361 non-null   object
 7   어른관람료      1361 non-null   int32
 8   청소년관람료     1361 non-null   int32
 9   어린이관람료     1361 non-null   int32
 10  데이터기준일자    1361 non-null   object
 11  평일관람가능시간   1361 non-null   float64
 12  공휴일관람가능시간  1361 non-null   float64
dtypes: float64(2), int32(3), object(8)
memory usage: 132.9+ KB

In [13]:
# 소재지도로명주소 컬럼을 활용하여 광역자치단체(광역), 기초자치단체(기초) 컬럼 추가
# 이때 세종특별시는 세종특별자치시로 이름 변경됨
# 또한 세종특별자치시는 기초자치단체가 없으므로 기초 컬럼에 NaN 저장
def get_basic(df):
    if df['광역'] == '세종특별자치시':
        return pd.NA
    else:
        return df['소재지도로명주소'].split()[1]
    
def get_detail(df):
    if df['광역'] == '세종특별자치시':
        start = 1
    else:
        start = 2
    return ' '.join(df['소재지도로명주소'].split()[start:])

tmp_df = df_target.copy()

tmp_df['소재지도로명주소'] = tmp_df['소재지도로명주소'].str.strip()

tmp_df['광역'] = tmp_df['소재지도로명주소'].str.split().str[0]
tmp_df['광역'] = tmp_df['광역'].apply(lambda x: '세종특별자치시' if x == '세종특별시' else x)

tmp_df['기초'] = tmp_df.apply(get_basic, axis=1)

tmp_df['상세'] = tmp_df.apply(get_detail, axis=1)

df_target = tmp_df.copy()
df_target.head(1)

,시설명,박물관미술관구분,소재지도로명주소,평일관람시작시각,평일관람종료시각,공휴일관람시작시각,공휴일관람종료시각,어른관람료,청소년관람료,어린이관람료,데이터기준일자,평일관람가능시간,공휴일관람가능시간,광역,기초,상세
0,풀짚공예박물관,사립,경기도 광주시 오포읍 문형산길 76,09:30,18:00,10:00,18:00,3000,1500,1500,2022-06-16,8.5,8.0,경기도,광주시,오포읍 문형산길 76

In [14]:
# 광역자치단체별 박물관/미술관 총 수 확인
# 우선순위에 따라 나열
province_dict = {
    '서울특별시': 0,
    '부산광역시': 1,
    '대구광역시': 2,
    '인천광역시': 3,
    '광주광역시': 4,
    '대전광역시': 5,
    '울산광역시': 6,
    '세종특별자치시': 7,
    '경기도': 8,
    '강원도': 9,
    '충청북도': 10,
    '충청남도': 11,
    '전라북도': 12,
    '전라남도': 13,
    '경상북도': 14,
    '경상남도': 15,
    '제주특별자치도': 16
}

tmp_df = df_target.copy()

tmp_df = tmp_df.groupby('광역').size().reset_index(name='박물관미술관수')

tmp_df['광역'] = pd.Categorical(
    tmp_df['광역'],
    categories=list(province_dict.keys()),
    ordered=True
)

tmp_df = tmp_df.sort_values('광역').set_index('광역')

df_result = tmp_df.copy()
df_result

         박물관미술관수
광역
서울특별시        198
부산광역시         48
대구광역시         23
인천광역시         42
광주광역시         49
대전광역시         23
울산광역시         11
세종특별자치시        8
경기도          219
강원도          133
충청북도          62
충청남도          76
전라북도          81
전라남도         107
경상북도          89
경상남도          97
제주특별자치도       95

In [15]:
# 광역-기초의 박물관/미술관 수가 8개인 지역 추출
tmp_df = df_target.copy()

tmp_df = tmp_df.groupby(['광역', '기초'], dropna=False).size().reset_index(name='박물관미술관수')

tmp_df = tmp_df[tmp_df['박물관미술관수'] == 8]

tmp_df['광역'] = pd.Categorical(
    tmp_df['광역'],
    categories=list(province_dict.keys()),
    ordered=True
)

tmp_df = tmp_df.sort_values(['광역', '기초'], ascending=[True, False]).reset_index(drop=True)

df_result = tmp_df.copy()
df_result

        광역    기초  박물관미술관수
0    부산광역시  해운대구        8
1    인천광역시  미추홀구        8
2  세종특별자치시   NaN        8
3      경기도   화성시        8
4      경기도   성남시        8
5     충청남도   예산군        8
6     전라남도   영암군        8
7     전라남도   강진군        8

In [ ]:
# 광역자치단체-박물관미술관구분 컬럼에 따른 평균 관람료 차이가 가장 크고 작은 곳 추출
import numpy as np

tmp_df = df_target.copy()

tmp_df = tmp_df[(tmp_df['어른관람료'] != 0) & (tmp_df['어린이관람료'] != 0)]

tmp_df['관람료차이'] = tmp_df['어른관람료'] - tmp_df['어린이관람료']

tmp_df = tmp_df.groupby(['광역', '박물관미술관구분'], dropna=True)[['어른관람료', '어린이관람료', '관람료차이']].mean().round(-1).astype(int).reset_index()

tmp_df['광역'] = pd.Categorical(
    tmp_df['광역'],
    categories=list(province_dict.keys()),
    ordered=True
)

tmp_df = tmp_df.sort_values('광역').set_index(['광역', '박물관미술관구분'])

tmp_df = tmp_df[(tmp_df['관람료차이'] == min(tmp_df['관람료차이'])) |
          (tmp_df['관람료차이'] == max(tmp_df['관람료차이']))]

df_result = tmp_df.copy()
df_result

                  어른관람료  어린이관람료  관람료차이
광역      박물관미술관구분
세종특별자치시 사립         2500    3000   -500
제주특별자치도 사립        10670    7710   2960

In [ ]:
# 가족(어른2, 청소년1, 어린이1)이 공휴일에 제주특별자치도 서귀포시에 있는 미술관을 관람하려할 때,
# 총 관람료가 2만원 이하, 공휴일 4시간 이상 관람 가능한 미술관 추출
budget = 20000
tmp_df = df_target.copy()

tmp_df = tmp_df[tmp_df['기초'] == '제주시']

gallery_name = ['미술관', '갤러리', '아트']
tmp_df = tmp_df[tmp_df['시설명'].str.contains('|'.join(gallery_name))]

tmp_df = tmp_df[tmp_df['공휴일관람가능시간'] >= 4]

tmp_df = tmp_df[tmp_df['어른관람료'] * 2 + tmp_df['청소년관람료'] + tmp_df['어린이관람료'] <= budget]

df_result = tmp_df.copy()
df_result.head(1)

,시설명,박물관미술관구분,소재지도로명주소,평일관람시작시각,평일관람종료시각,공휴일관람시작시각,공휴일관람종료시각,어른관람료,청소년관람료,어린이관람료,데이터기준일자,평일관람가능시간,공휴일관람가능시간,광역,기초,상세
1107,제주옹기숨미술관,사립,제주특별자치도 제주시 주르레길 55-19(해안동),10:00,17:00,10:00,17:00,0,0,0,2022-06-16,7.0,7.0,제주특별자치도,제주시,주르레길 55-19(해안동)