In [2]:
# Raw Data Loading
import pandas as pd

df_target = pd.read_csv('./서울시 지하철 호선별 역별 유_무임 승하차 인원 정보.csv', encoding='cp949')
df_target.head()

      사용월  호선명          지하철역   유임승차인원  무임승차인원   유임하차인원  무임하차인원      작업일자
0  202206  1호선           제기동   218782  263173   209109  281985  20220703
1  202206  1호선  청량리(서울시립대입구)   328288  246164   325365  249818  20220703
2  202206  1호선            종각   834173  131987   815704  121717  20220703
3  202206  1호선           서울역  1150754  194717  1123193  187155  20220703
4  202206  1호선          종로3가   450317  299617   404106  278151  20220703

In [3]:
df_target.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60060 entries, 0 to 60059
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사용월     60060 non-null  int64
 1   호선명     60060 non-null  object
 2   지하철역    60060 non-null  object
 3   유임승차인원  60060 non-null  int64
 4   무임승차인원  60060 non-null  int64
 5   유임하차인원  60060 non-null  int64
 6   무임하차인원  60060 non-null  int64
 7   작업일자    60060 non-null  int64
dtypes: int64(6), object(2)
memory usage: 3.7+ MB

In [ ]:
# 중복 데이터 제거
tmp_df = df_target.copy()
tmp_df = tmp_df.drop_duplicates(keep='first')

df_target = tmp_df.copy()
df_target.head()

      사용월  호선명          지하철역   유임승차인원  무임승차인원   유임하차인원  무임하차인원      작업일자
0  202206  1호선           제기동   218782  263173   209109  281985  20220703
1  202206  1호선  청량리(서울시립대입구)   328288  246164   325365  249818  20220703
2  202206  1호선            종각   834173  131987   815704  121717  20220703
3  202206  1호선           서울역  1150754  194717  1123193  187155  20220703
4  202206  1호선          종로3가   450317  299617   404106  278151  20220703

In [5]:
df_target.info()

<class 'pandas.core.frame.DataFrame'>
Index: 51162 entries, 0 to 60059
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사용월     51162 non-null  int64
 1   호선명     51162 non-null  object
 2   지하철역    51162 non-null  object
 3   유임승차인원  51162 non-null  int64
 4   무임승차인원  51162 non-null  int64
 5   유임하차인원  51162 non-null  int64
 6   무임하차인원  51162 non-null  int64
 7   작업일자    51162 non-null  int64
dtypes: int64(6), object(2)
memory usage: 3.5+ MB

In [ ]:
# 사용월, 호선명, 지하철역의 데이터가 중복되는 행에 대해서
# 유임승차인원, 무임승차인원, 유임하차인원, 무임하차인원에 각각 합한 값을 저장하고
# 첫번째 데이터만 남기기
drop_columns = ['사용월','호선명','지하철역']
sum_columns = ['유임승차인원', '무임승차인원', '유임하차인원', '무임하차인원']

tmp_df = df_target.copy()

tmp_df[sum_columns] = tmp_df.groupby(drop_columns)[sum_columns].transform('sum')

tmp_df = tmp_df.drop_duplicates(subset=drop_columns, keep='first')

df_target = tmp_df.copy()
df_target.head()

      사용월  호선명          지하철역   유임승차인원  무임승차인원   유임하차인원  무임하차인원      작업일자
0  202206  1호선           제기동   218782  263173   209109  281985  20220703
1  202206  1호선  청량리(서울시립대입구)   328288  246164   325365  249818  20220703
2  202206  1호선            종각   834173  131987   815704  121717  20220703
3  202206  1호선           서울역  1150754  194717  1123193  187155  20220703
4  202206  1호선          종로3가   450317  299617   404106  278151  20220703

In [7]:
df_target['호선명'].unique()

array(['1호선', '2호선', '3호선', '4호선', '5호선', '6호선', '7호선', '8호선', '9호선',
       '9호선2~3단계', '경강선', '경부선', '경원선', '경의선', '경인선', '경춘선', '공항철도 1호선',
       '과천선', '분당선', '수인선', '신림선', '안산선', '우이신설선', '일산선', '장항선', '중앙선',
       '9호선2단계'], dtype=object)

In [8]:
# 호선명이 9호선2~3단계 또는 9호선2단계인 데이터를 9호선으로 변경
# 지하철역 컬럼의 데이터에 괄호 '(', ')'가 있다면 괄호와 괄호 안의 내용 삭제
# 지하철역 컬럼의 데이터가 신천이라면 잠실새내로 변경 
tmp_df = df_target.copy()

tmp_df['호선명'] = tmp_df['호선명'].replace(['9호선2~3단계', '9호선2단계'], '9호선')
tmp_df['지하철역'] = tmp_df['지하철역'].str.split('(').str[0].str.strip()
tmp_df['지하철역'] = tmp_df['지하철역'].replace('신천', '잠실새내')

df_target = tmp_df.copy()
df_target.head()

      사용월  호선명  지하철역   유임승차인원  무임승차인원   유임하차인원  무임하차인원      작업일자
0  202206  1호선   제기동   218782  263173   209109  281985  20220703
1  202206  1호선   청량리   328288  246164   325365  249818  20220703
2  202206  1호선    종각   834173  131987   815704  121717  20220703
3  202206  1호선   서울역  1150754  194717  1123193  187155  20220703
4  202206  1호선  종로3가   450317  299617   404106  278151  20220703

In [9]:
df_target['호선명'].unique()

array(['1호선', '2호선', '3호선', '4호선', '5호선', '6호선', '7호선', '8호선', '9호선',
       '경강선', '경부선', '경원선', '경의선', '경인선', '경춘선', '공항철도 1호선', '과천선', '분당선',
       '수인선', '신림선', '안산선', '우이신설선', '일산선', '장항선', '중앙선'], dtype=object)

In [ ]:
# incheon_station_list는 모두 7호선의 역이며 서울특별시가 관리하는 역이 아님
# 따라서 리스트에 있는 역들의 호선명 데이터를 '7호선'에서 '7호선 인천'으로 변경
incheon_station_list = ['까치울', '부천종합운동장', '춘의', '신중동', '부천시청', '상동', '삼산체육관', '굴포천', '부평구청', '산곡', '석남']

tmp_df = df_target.copy()

tmp_df.loc[(tmp_df['호선명'] == '7호선') &
           (tmp_df['지하철역'].isin(incheon_station_list)),
           '호선명'] = '7호선 인천'

df_target = tmp_df.copy()
df_target.head()

      사용월  호선명  지하철역   유임승차인원  무임승차인원   유임하차인원  무임하차인원      작업일자
0  202206  1호선   제기동   218782  263173   209109  281985  20220703
1  202206  1호선   청량리   328288  246164   325365  249818  20220703
2  202206  1호선    종각   834173  131987   815704  121717  20220703
3  202206  1호선   서울역  1150754  194717  1123193  187155  20220703
4  202206  1호선  종로3가   450317  299617   404106  278151  20220703

In [11]:
df_target['호선명'].unique()

array(['1호선', '2호선', '3호선', '4호선', '5호선', '6호선', '7호선', '7호선 인천', '8호선',
       '9호선', '경강선', '경부선', '경원선', '경의선', '경인선', '경춘선', '공항철도 1호선', '과천선',
       '분당선', '수인선', '신림선', '안산선', '우이신설선', '일산선', '장항선', '중앙선'],
      dtype=object)

In [ ]:
# 2022년 6월 기준 각 지하철역의
# 유임승차인원, 무임승차인원, 유임하차인원, 무임하차인원 합산
columns = ['유임승차인원', '무임승차인원', '유임하차인원', '무임하차인원']

tmp_df = df_target.copy()

tmp_df = tmp_df[tmp_df['사용월'] == 202206]
tmp_df = tmp_df.groupby('지하철역')[columns].sum()

df_result = tmp_df.copy()
df_result.head()

           유임승차인원  무임승차인원   유임하차인원  무임하차인원
지하철역
4.19민주묘지    56275   34889    54138   30800
가능         139026   55693   131155   54568
가락시장       322711  129590   342636  128815
가산디지털단지   1431139  117639  1502220  117128
가양         456785  123819   442530  120665

In [ ]:
# 2022년 6월 기준 각 지하철역의 호선의 수가 3개 이상인 역
tmp_df = df_target.copy()

tmp_df = tmp_df[tmp_df['사용월'] == 202206]
tmp_df = tmp_df.groupby(['지하철역'])['호선명'].nunique()
tmp_df = tmp_df[tmp_df >= 3].reset_index()

tmp_df.columns = ['지하철역', '호선수']
tmp_df = tmp_df.set_index('지하철역')
tmp_df = tmp_df.sort_values(by=['호선수', '지하철역'], ascending=[False, False])

df_result = tmp_df.copy()
df_result.head()

      호선수
지하철역
서울역     5
공덕      4
홍대입구    3
종로3가    3
왕십리     3

In [ ]:
# 위에서 구한 호선수가 3개 이상인 역과 해당 역의 환승 가능 호선 구하기
tmp_df = df_target.copy()

tmp_df = tmp_df[tmp_df['사용월'] == 202206]

line_df = tmp_df.groupby('지하철역')['호선명'].nunique()
transfer_df = tmp_df.groupby('지하철역')['호선명'].apply(lambda x: ', '.join(sorted(x.unique())))

tmp_df = pd.concat([line_df, transfer_df], axis=1)
tmp_df.columns = ['호선수', '환승호선']

tmp_df = tmp_df[tmp_df['호선수'] >= 3]
tmp_df = tmp_df.sort_values(by=['호선수', '환승호선'], ascending=[False, True])

df_result = tmp_df.copy()
df_result.head()

           호선수                          환승호선
지하철역
서울역          5  1호선, 4호선, 경부선, 경의선, 공항철도 1호선
공덕           4       5호선, 6호선, 경의선, 공항철도 1호선
신설동          3               1호선, 2호선, 우이신설선
종로3가         3                 1호선, 3호선, 5호선
동대문역사문화공원    3                 2호선, 4호선, 5호선

In [ ]:
# 호선수가 3개 이상인 지하철역들의 유임승하차율, 무임승하차율, 승하차율 컬럼 추가하기
# 그 중 무임승하차율이 승하차율보다 크고, 102 이상인 역 출력
import warnings

warnings.filterwarnings('ignore')

def get_ratio(df, ratio_type):
    if ratio_type == '유임승하차율':
        return round(df['유임승차인원'].sum() / df['유임하차인원'].sum() * 100, 2)
    elif ratio_type == '무임승하차율':
        return round(df['무임승차인원'].sum() / df['무임하차인원'].sum() * 100, 2)
    elif ratio_type == '승하차율':
        return round((df['유임승차인원'].sum() + df['무임승차인원'].sum()) / 
                     (df['유임하차인원'].sum() + df['무임하차인원'].sum()) * 100, 2)


ratio_columns = ['유임승하차율', '무임승하차율', '승하차율']
columns = ['유임승차인원', '무임승차인원', '유임하차인원', '무임하차인원']

tmp_df = df_target.copy()

tmp_df = tmp_df[tmp_df['사용월'] == 202206]

line_df = tmp_df.groupby('지하철역')['호선명'].nunique()
line_df = line_df[line_df >= 2]

ratio_df = pd.DataFrame(index=line_df.index)
for col in ratio_columns:
    ratio_df[col] = tmp_df.groupby('지하철역')[columns].apply(get_ratio, col)

ratio_df['호선수'] = line_df

ratio_df = ratio_df[(ratio_df['무임승하차율'] > ratio_df['승하차율']) &
                    (ratio_df['무임승하차율'] >= 102)]

ratio_df = ratio_df[['호선수'] + ratio_columns]
ratio_df = ratio_df.sort_values(by=['호선수', '무임승하차율'], ascending=[False, False])

df_result = ratio_df.copy()
df_result

        호선수  유임승하차율  무임승하차율    승하차율
지하철역
서울역       5   98.69  102.94   99.21
공덕        4   97.96  104.65   98.79
홍대입구      3   92.93  103.17   93.43
종로3가      3  100.54  102.67  101.21
고속터미널     3   99.67  102.58  100.07
왕십리       3  101.06  102.29  101.22
여의도       2   97.69  106.58   98.23
시청        2  101.17  106.16  101.69
청구        2  102.47  105.86  103.14
삼각지       2  101.20  105.85  101.74
올림픽공원     2  104.39  105.25  104.55
도곡        2   99.71  105.15  100.79
이촌        2  100.87  105.01  101.73
약수        2  101.73  104.95  102.40
잠실        2   98.08  104.49   98.72
선릉        2   98.43  104.26   99.18
보라매       2  102.35  103.77  102.60
교대        2  100.96  103.64  101.41
태릉입구      2   99.43  103.43  100.12
신도림       2   98.65  102.74   99.24
성신여대입구    2  101.68  102.65  101.83
을지로3가     2   98.09  102.58   98.67
합정        2   94.15  102.36   94.77

In [ ]:
# 2022년 1월 대비 2022년 6월에 유동인구 증감율 구하기
# 이 중 유동인구가 감소한(유동인구 증감율이 0보다 작은) 역 출력
columns = ['유임승차인원', '무임승차인원', '유임하차인원', '무임하차인원']

tmp_df = df_target.copy()

tmp_df = tmp_df[tmp_df['호선명'] != '7호선 인천']

jan_df = tmp_df[tmp_df['사용월'] == 202201]
jun_df = tmp_df[tmp_df['사용월'] == 202206]

jan_df['유동인구'] = jan_df[columns].sum(axis=1)
jun_df['유동인구'] = jun_df[columns].sum(axis=1)

jan_df = jan_df.set_index('지하철역')
jun_df = jun_df.set_index('지하철역')

jan_df = jan_df.groupby('지하철역')['유동인구'].sum()
jun_df = jun_df.groupby('지하철역')['유동인구'].sum()

tmp_df = pd.DataFrame({
    '유동인구_1월': jan_df,
    '유동인구_6월': jun_df
})

tmp_df = tmp_df.dropna()

tmp_df['유동인구증감률'] = round((tmp_df['유동인구_6월'] / tmp_df['유동인구_1월'] - 1) * 100, 2)
tmp_df = tmp_df[tmp_df['유동인구증감률'] < 0][['유동인구증감률']]
tmp_df = tmp_df.sort_values(by='유동인구증감률', ascending=False)

df_result = tmp_df.copy()
df_result

      유동인구증감률
지하철역
논현      -1.29
신사      -2.74
구반포     -2.87
사릉     -10.15
당고개    -22.42
백양리    -62.19

In [ ]:
# 2015년에서 2022년까지 지하철 1~9호선에서 신설된 역 확인
# 해당 기간 중 유동인구 데이터가 존재하지 않는 경우 해당 기간에는 해당 역은 존재하지 않는다고 간주
columns = ['유임승차인원', '무임승차인원', '유임하차인원', '무임하차인원']
lines = [f'{i}호선' for i in range(1, 10)]

tmp_df = df_target.copy()

tmp_df = tmp_df[tmp_df['호선명'].isin(lines)]
tmp_df = tmp_df[(tmp_df['사용월'] >= 201501) &
                (tmp_df['사용월'] <= 202206)]

tmp_df['유동인구'] = tmp_df[columns].sum(axis=1)
tmp_df = tmp_df[tmp_df['유동인구'] > 0]
tmp_df = tmp_df.groupby(['호선명', '지하철역'])['사용월'].min()

tmp_df = tmp_df.reset_index()
tmp_df.columns = ['호선명', '지하철역', '신설월']
tmp_df = tmp_df.loc[tmp_df.groupby('지하철역')['신설월'].idxmin()]
tmp_df = tmp_df[tmp_df['신설월'] != 201501]

tmp_df = tmp_df.sort_values(by=['호선명', '신설월', '지하철역'], ascending=[True, False, True]).reset_index(drop=True)

df_result = tmp_df.copy()
df_result

    호선명    지하철역     신설월
0   5호선      강일  202103
1   5호선   하남검단산  202103
2   5호선    하남시청  202103
3   5호선      미사  202008
4   5호선    하남풍산  202008
5   6호선      신내  201912
6   8호선     남위례  202112
7   9호선    둔촌오륜  201812
8   9호선      삼전  201812
9   9호선    석촌고분  201812
10  9호선    송파나루  201812
11  9호선  중앙보훈병원  201812
12  9호선    한성백제  201812
13  9호선     봉은사  201503
14  9호선    삼성중앙  201503
15  9호선     선정릉  201503
16  9호선      언주  201503