In [2]:
import warnings

warnings.filterwarnings('ignore')

In [3]:
# Raw Data Loading
import pandas as pd

df_target = pd.read_csv('./교통사고+현황(사고유형별).csv')
df_target.head()

,자치구별(1),자치구별(2),사고유형별(1),사고유형별(2),구분별(1),1988,1989,1990,1991,1992,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,합계,소계,합계,소계,발생건수 (건),-,-,-,-,-,...,40829,39439,40792,41665,40039,38625,38795,39258,35227,33913
1,합계,소계,합계,소계,사망자수 (명),-,-,-,-,-,...,424,378,400,376,348,343,304,250,219,243
2,합계,소계,합계,소계,부상자수 (명),-,-,-,-,-,...,58583,56761,57345,58656,55669,53810,53751,53904,47513,45223
3,합계,소계,차대사람,소계,발생건수 (건),30877,35109,33606,33061,27165,...,10892,10683,11118,11318,10683,10249,9978,9896,7671,7075
4,합계,소계,차대사람,소계,사망자수 (명),-,-,-,-,-,...,235,215,214,211,196,189,182,139,113,120

In [4]:
df_target.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 318 entries, 0 to 317
Data columns (total 39 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   자치구별(1)   318 non-null    object
 1   자치구별(2)   318 non-null    object
 2   사고유형별(1)  318 non-null    object
 3   사고유형별(2)  318 non-null    object
 4   구분별(1)    318 non-null    object
 5   1988      318 non-null    object
 6   1989      318 non-null    object
 7   1990      318 non-null    object
 8   1991      318 non-null    object
 9   1992      318 non-null    object
 10  1993      318 non-null    object
 11  1994      318 non-null    object
 12  1995      318 non-null    object
 13  1996      318 non-null    object
 14  1997      318 non-null    object
 15  1998      318 non-null    object
 16  1999      318 non-null    object
 17  2000      318 non-null    object
 18  2001      318 non-null    object
 19  2002      318 non-null    object
 20  2003      318 non-null    object
 21  2004      318 non-null    object
 22  2005      318 non-null    object
 23  2006      318 non-null    object
 24  2007      318 non-null    object
 25  2008      318 non-null    object
 26  2009      318 non-null    object
 27  2010      318 non-null    object
 28  2011      318 non-null    object
 29  2012      318 non-null    object
 30  2013      318 non-null    object
 31  2014      318 non-null    object
 32  2015      318 non-null    object
 33  2016      318 non-null    object
 34  2017      318 non-null    object
 35  2018      318 non-null    object
 36  2019      318 non-null    object
 37  2020      318 non-null    object
 38  2021      317 non-null    object
dtypes: object(39)
memory usage: 97.0+ KB

In [5]:
# 컬럼 정리
# '자치구별(1)', '사고유형별(2)' 컬럼 삭제
# '자치구별(2)' -> '자치구', '사고유형별(1)' -> '사고유형', '구분별(1)' -> '구분'
# 으로 컬럼명 수정
drop_columns = ['자치구별(1)', '사고유형별(2)']
rename_columns = {
    '자치구별(2)': '자치구',
    '사고유형별(1)': '사고유형',
    '구분별(1)': '구분'
}

tmp_df = df_target.copy()

tmp_df = tmp_df.drop(columns=drop_columns)
tmp_df = tmp_df.rename(columns=rename_columns)

df_target = tmp_df.copy()
df_target.head()

,자치구,사고유형,구분,1988,1989,1990,1991,1992,1993,1994,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,소계,합계,발생건수 (건),-,-,-,-,-,-,-,...,40829,39439,40792,41665,40039,38625,38795,39258,35227,33913
1,소계,합계,사망자수 (명),-,-,-,-,-,-,-,...,424,378,400,376,348,343,304,250,219,243
2,소계,합계,부상자수 (명),-,-,-,-,-,-,-,...,58583,56761,57345,58656,55669,53810,53751,53904,47513,45223
3,소계,차대사람,발생건수 (건),30877,35109,33606,33061,27165,23245,19590,...,10892,10683,11118,11318,10683,10249,9978,9896,7671,7075
4,소계,차대사람,사망자수 (명),-,-,-,-,-,-,-,...,235,215,214,211,196,189,182,139,113,120

In [6]:
df_target.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 318 entries, 0 to 317
Data columns (total 37 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   자치구     318 non-null    object
 1   사고유형    318 non-null    object
 2   구분      318 non-null    object
 3   1988    318 non-null    object
 4   1989    318 non-null    object
 5   1990    318 non-null    object
 6   1991    318 non-null    object
 7   1992    318 non-null    object
 8   1993    318 non-null    object
 9   1994    318 non-null    object
 10  1995    318 non-null    object
 11  1996    318 non-null    object
 12  1997    318 non-null    object
 13  1998    318 non-null    object
 14  1999    318 non-null    object
 15  2000    318 non-null    object
 16  2001    318 non-null    object
 17  2002    318 non-null    object
 18  2003    318 non-null    object
 19  2004    318 non-null    object
 20  2005    318 non-null    object
 21  2006    318 non-null    object
 22  2007    318 non-null    object
 23  2008    318 non-null    object
 24  2009    318 non-null    object
 25  2010    318 non-null    object
 26  2011    318 non-null    object
 27  2012    318 non-null    object
 28  2013    318 non-null    object
 29  2014    318 non-null    object
 30  2015    318 non-null    object
 31  2016    318 non-null    object
 32  2017    318 non-null    object
 33  2018    318 non-null    object
 34  2019    318 non-null    object
 35  2020    318 non-null    object
 36  2021    317 non-null    object
dtypes: object(37)
memory usage: 92.1+ KB

In [7]:
# '구분' 컬럼의 데이터 중 괄호와 괄호 안의 내용 삭제
tmp_df = df_target.copy()

tmp_df['구분'] = tmp_df['구분'].str.split('(').str[0]
tmp_df['구분'] = tmp_df['구분'].str.strip()

df_target = tmp_df.copy()
df_target.head()

,자치구,사고유형,구분,1988,1989,1990,1991,1992,1993,1994,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,소계,합계,발생건수,-,-,-,-,-,-,-,...,40829,39439,40792,41665,40039,38625,38795,39258,35227,33913
1,소계,합계,사망자수,-,-,-,-,-,-,-,...,424,378,400,376,348,343,304,250,219,243
2,소계,합계,부상자수,-,-,-,-,-,-,-,...,58583,56761,57345,58656,55669,53810,53751,53904,47513,45223
3,소계,차대사람,발생건수,30877,35109,33606,33061,27165,23245,19590,...,10892,10683,11118,11318,10683,10249,9978,9896,7671,7075
4,소계,차대사람,사망자수,-,-,-,-,-,-,-,...,235,215,214,211,196,189,182,139,113,120

In [8]:
df_target.columns

Index(['자치구', '사고유형', '구분', '1988', '1989', '1990', '1991', '1992', '1993',
       '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002',
       '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011',
       '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020',
       '2021'],
      dtype='object')

In [ ]:
# '1988' ~ '2021' 컬럼의 데이터 중 결측치는 '-'으로 저장되어 있으므로 0으로 수정
# 이후 현재 object 타입인 '1988' ~ '2021' 컬럼들의 타입을 int 타입으로 변경
columns = [str(i) for i in range(1988, 2022)]

tmp_df = df_target.copy()

tmp_df[columns] = tmp_df[columns].replace('-', 0)
tmp_df[columns] = tmp_df[columns].fillna(0)
tmp_df[columns] = tmp_df[columns].astype(int)

df_target = tmp_df.copy()
df_target.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 318 entries, 0 to 317
Data columns (total 37 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   자치구     318 non-null    object
 1   사고유형    318 non-null    object
 2   구분      318 non-null    object
 3   1988    318 non-null    int32
 4   1989    318 non-null    int32
 5   1990    318 non-null    int32
 6   1991    318 non-null    int32
 7   1992    318 non-null    int32
 8   1993    318 non-null    int32
 9   1994    318 non-null    int32
 10  1995    318 non-null    int32
 11  1996    318 non-null    int32
 12  1997    318 non-null    int32
 13  1998    318 non-null    int32
 14  1999    318 non-null    int32
 15  2000    318 non-null    int32
 16  2001    318 non-null    int32
 17  2002    318 non-null    int32
 18  2003    318 non-null    int32
 19  2004    318 non-null    int32
 20  2005    318 non-null    int32
 21  2006    318 non-null    int32
 22  2007    318 non-null    int32
 23  2008    318 non-null    int32
 24  2009    318 non-null    int32
 25  2010    318 non-null    int32
 26  2011    318 non-null    int32
 27  2012    318 non-null    int32
 28  2013    318 non-null    int32
 29  2014    318 non-null    int32
 30  2015    318 non-null    int32
 31  2016    318 non-null    int32
 32  2017    318 non-null    int32
 33  2018    318 non-null    int32
 34  2019    318 non-null    int32
 35  2020    318 non-null    int32
 36  2021    318 non-null    int32
dtypes: int32(34), object(3)
memory usage: 49.8+ KB

In [ ]:
# '자치구' 컬럼의 데이터 중 '소계' 데이터를 '서울시'로 변경
# '자치구', '사고유형', '구분' 별로 groupby
groupby_columns = ['자치구', '사고유형', '구분']

tmp_df = df_target.copy()
tmp_df.loc[tmp_df['자치구'] == '소계', '자치구'] = '서울시'

tmp_df = tmp_df.groupby(groupby_columns, sort=False).sum()

df_target = tmp_df.copy()
df_target.head()

                1988   1989   1990   1991   1992   1993   1994   1995   1996  \
자치구 사고유형 구분
서울시 합계   발생건수      0      0      0      0      0      0      0      0      0
         사망자수      0      0      0      0      0      0      0      0      0
         부상자수      0      0      0      0      0      0      0      0      0
    차대사람 발생건수  30877  35109  33606  33061  27165  23245  19590  16653  16098
         사망자수      0      0      0      0      0      0      0      0      0

                1997  ...   2012   2013   2014   2015   2016   2017   2018  \
자치구 사고유형 구분           ...
서울시 합계   발생건수      0  ...  40829  39439  40792  41665  40039  38625  38795
         사망자수      0  ...    424    378    400    376    348    343    304
         부상자수      0  ...  58583  56761  57345  58656  55669  53810  53751
    차대사람 발생건수  13086  ...  10892  10683  11118  11318  10683  10249   9978
         사망자수      0  ...    235    215    214    211    196    189    182

                2019   2020   2021
자치구 사고유형 구분
서울시 합계   발생건수  39258  35227  33913
         사망자수    250    219    243
         부상자수  53904  47513  45223
    차대사람 발생건수   9896   7671   7075
         사망자수    139    113    120

[5 rows x 34 columns]

In [ ]:
# 값이 0인 '1988' ~ '2004' 컬럼의 '자치구'-'합계'-'발생건수' 행의 데이터 채우기
# 서울시 포함 각 자치구의 '합계'-'발생건수'는
# ('차대사람'-'발생건수') + ('차대차'-'발생건수') + ('차량단독'-'발생건수') + ('건널목'-'발생건수')
# 이때 '차대사람', '차대차', '차량단독', '건널목' 행이 없는 경우가 있으므로 주의
columns = [str(i) for i in range(1988, 2005)]

tmp_df = df_target.copy()

for gu in tmp_df.index.get_level_values(0).unique():
    target_idx = (gu, '합계', '발생건수')

    idx_list = [
        (gu, '차대사람', '발생건수'),
        (gu, '차대차', '발생건수'),
        (gu, '차량단독', '발생건수'),
        (gu, '건널목', '발생건수')
    ]

    exist_idx = [idx for idx in target_idx if idx in tmp_df.index]

    sum_value = tmp_df.loc[exist_idx, columns].sum()

    is_zero = tmp_df.loc[target_idx, columns] == 0
    tmp_df.loc[target_idx, columns] = tmp_df.loc[target_idx, columns].mask(is_zero, sum_value)

df_target = tmp_df.copy()
df_target.head()

                1988   1989   1990   1991   1992   1993   1994   1995   1996  \
자치구 사고유형 구분
서울시 합계   발생건수  56008  63835  58231  56528  51333  49422  46479  42100  46031
         사망자수      0      0      0      0      0      0      0      0      0
         부상자수      0      0      0      0      0      0      0      0      0
    차대사람 발생건수  30877  35109  33606  33061  27165  23245  19590  16653  16098
         사망자수      0      0      0      0      0      0      0      0      0

                1997  ...   2012   2013   2014   2015   2016   2017   2018  \
자치구 사고유형 구분           ...
서울시 합계   발생건수  40863  ...  40829  39439  40792  41665  40039  38625  38795
         사망자수      0  ...    424    378    400    376    348    343    304
         부상자수      0  ...  58583  56761  57345  58656  55669  53810  53751
    차대사람 발생건수  13086  ...  10892  10683  11118  11318  10683  10249   9978
         사망자수      0  ...    235    215    214    211    196    189    182

                2019   2020   2021
자치구 사고유형 구분
서울시 합계   발생건수  39258  35227  33913
         사망자수    250    219    243
         부상자수  53904  47513  45223
    차대사람 발생건수   9896   7671   7075
         사망자수    139    113    120

[5 rows x 34 columns]

In [ ]:
# '구분' 인덱스 삭제 (발생건수만 추출)
df_result = df_target.xs('발생건수', level='구분')

df_result

           1988   1989   1990   1991   1992   1993   1994   1995   1996  \
자치구 사고유형
서울시 합계    56008  63835  58231  56528  51333  49422  46479  42100  46031
    차대사람  30877  35109  33606  33061  27165  23245  19590  16653  16098
    차대차   23899  27129  23734  22949  23724  25876  26475  24927  29406
    차량단독   1210   1592    891    516    443    300    412    520    527
    건널목      22      5      0      2      1      1      2      0      0
...         ...    ...    ...    ...    ...    ...    ...    ...    ...
송파구 차량단독      0      0      0      0      0      0      0      0      0
강동구 합계        0      0      0      0      0      0      0      0      0
    차대사람      0      0      0      0      0      0      0      0      0
    차대차       0      0      0      0      0      0      0      0      0
    차량단독      0      0      0      0      0      0      0      0      0

           1997  ...   2012   2013   2014   2015   2016   2017   2018   2019  \
자치구 사고유형         ...
서울시 합계    40863  ...  40829  39439  40792  41665  40039  38625  38795  39258
    차대사람  13086  ...  10892  10683  11118  11318  10683  10249   9978   9896
    차대차   27414  ...  28537  27358  28201  28854  28030  27103  27522  28150
    차량단독    363  ...   1399   1398   1473   1493   1326   1273   1295   1212
    건널목       0  ...      1      0      0      0      0      0      0      0
...         ...  ...    ...    ...    ...    ...    ...    ...    ...    ...
송파구 차량단독      0  ...     84    102     85     94     91     76    105     90
강동구 합계        0  ...   1458   1356   1442   1494   1426   1371   1418   1414
    차대사람      0  ...    438    402    452    479    426    427    394    437
    차대차       0  ...    970    915    963    963    959    906    978    944
    차량단독      0  ...     50     39     27     52     41     38     46     33

           2020   2021
자치구 사고유형
서울시 합계    35227  33913
    차대사람   7671   7075
    차대차   26508  25926
    차량단독   1048    912
    건널목       0      0
...         ...    ...
송파구 차량단독     53     57
강동구 합계     1268   1047
    차대사람    342    242
    차대차     890    788
    차량단독     36     17

[107 rows x 34 columns]

In [ ]:
# 서울시 포함 각 자치구의 사망자수 집계
type_list = ['합계', '차대사람', '차대차', '차량단독', '건널목']
gu_list = ['서울시', '종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구', '강북구', '도봉구', '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구', '금천구', '영등포구', '동작구', '관악구', '서초구', '강남구', '송파구', '강동구']
columns = [str(i) for i in range(2005, 2022)]

df_result = df_target.xs('사망자수', level='구분')
df_result = df_result[columns]

df_result = df_result.reorder_levels(['사고유형', '자치구'])

df_result.index = df_result.index.set_levels([
    pd.CategoricalIndex(df_result.index.levels[0], categories=type_list, ordered=True),
    pd.CategoricalIndex(df_result.index.levels[1], categories=gu_list, ordered=True)
])
df_result = df_result.sort_index(level=['사고유형','자치구'])

df_result.head()

          2005  2006  2007  2008  2009  2010  2011  2012  2013  2014  2015  \
사고유형 자치구
합계   서울시   485   452   452   482   501   429   435   424   378   400   376
     종로구    24    15    12    23    18    19    14    12    13    11     8
     중구     13    16    12    13    12     7    13    12    10     7     8
     용산구    20    14    20    19    20    15     9    11    13     8    18
     성동구    13    15    16    17    13    15    21     6     8    11     8

          2016  2017  2018  2019  2020  2021
사고유형 자치구
합계   서울시   348   343   304   250   219   243
     종로구     9    13     6     6     5     6
     중구     17     4     9     5     6     3
     용산구    12    12    14    10    12     5
     성동구    15    15     9    13     9     8

In [15]:
# 2005년 이후 서울시 포함 각 자치구 사망률 집계
type_list = ['합계', '차대사람', '차대차', '차량단독', '건널목']
gu_list = ['서울시', '종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구', '강북구', '도봉구', '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구', '금천구', '영등포구', '동작구', '관악구', '서초구', '강남구', '송파구', '강동구']
columns = [str(i) for i in range(2005, 2022)]

deaths = df_target.xs('사망자수', level='구분')[columns]
accidents = df_target.xs('발생건수', level='구분')[columns]
df_result = (deaths / accidents * 100).round(2)

df_result.index = df_result.index.set_levels([
    pd.CategoricalIndex(df_result.index.levels[0], categories=gu_list, ordered=True),
    pd.CategoricalIndex(df_result.index.levels[1], categories=type_list, ordered=True)
])
df_result = df_result.sort_index(level=['자치구', '사고유형'])
df_result = df_result.dropna()

df_result.head(10)

           2005  2006  2007   2008  2009  2010  2011  2012  2013  2014  2015  \
자치구 사고유형
서울시 합계     1.26  1.18  1.15   1.16  1.13  1.03  1.08  1.04  0.96  0.98  0.90
    차대사람   2.51  2.39  2.34   2.45  2.19  2.07  2.26  2.16  2.01  1.92  1.86
    차대차    0.68  0.64  0.59   0.56  0.63  0.50  0.46  0.48  0.44  0.53  0.40
    차량단독   7.91  6.95  7.02   5.06  4.36  4.46  4.66  3.79  3.00  2.44  3.28
종로구 합계     1.60  1.10  0.75   1.47  1.14  1.32  0.99  0.87  1.02  0.84  0.57
    차대사람   4.28  2.55  1.88   3.82  2.75  3.18  3.19  2.26  3.02  1.81  1.77
    차대차    0.60  0.49  0.25   0.27  0.43  0.60  0.00  0.32  0.00  0.35  0.00
    차량단독  11.76  6.25  5.41  10.42  4.69  1.64  2.08  0.00  3.70  1.45  1.30
중구  합계     0.98  1.15  0.85   0.91  0.78  0.45  0.87  0.82  0.69  0.54  0.60
    차대사람   2.15  3.69  2.80   2.08  2.61  0.56  2.74  1.86  1.99  0.28  2.14

          2016  2017  2018  2019  2020  2021
자치구 사고유형
서울시 합계    0.87  0.89  0.78  0.64  0.62  0.72
    차대사람  1.83  1.84  1.82  1.40  1.47  1.70
    차대차   0.43  0.43  0.35  0.30  0.30  0.35
    차량단독  2.41  2.91  2.01  2.23  2.48  3.40
종로구 합계    0.69  1.09  0.53  0.53  0.55  0.77
    차대사람  1.78  2.40  1.19  0.98  0.90  2.20
    차대차   0.23  0.37  0.26  0.38  0.31  0.18
    차량단독  0.00  4.26  0.00  0.00  3.12  2.78
중구  합계    1.32  0.32  0.80  0.42  0.63  0.35
    차대사람  3.19  0.32  1.37  1.41  0.42  1.16