In [1]:
import warnings

warnings.filterwarnings('ignore')

In [ ]:
import pandas as pd

# 서울시 구별/사고유형별 교통사고 현황
path = './교통사고+현황(사고유형별)_preprocessing.csv'
df_acc = pd.read_csv(path)
print('서울시 구별/사고유형별 교통사고 현황')
display(df_acc.head())

# 서울시 구별 차량통행속도
path = './차량통행속도(월별_구별).csv'
df_speed = pd.read_csv(path)
print('서울시 구별 차량통행속도')
display(df_speed.head())


# 서울시 구별 인구밀도(단위: 인구(명) / 면적(㎢) / 인구밀도(명/㎢))
path = './인구밀도.csv'
df_density = pd.read_csv(path)
print('서울시 구별 인구밀도')
display(df_density.head())

서울시 구별/사고유형별 교통사고 현황

,자치구,사고유형,구분,1988,1989,1990,1991,1992,1993,1994,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,서울시,합계,발생건수,56008,63835,58231,56528,51333,49422,46479,...,40829,39439,40792,41665,40039,38625,38795,39258,35227,33913
1,서울시,합계,사망자수,0,0,0,0,0,0,0,...,424,378,400,376,348,343,304,250,219,243
2,서울시,합계,부상자수,0,0,0,0,0,0,0,...,58583,56761,57345,58656,55669,53810,53751,53904,47513,45223
3,서울시,차대사람,발생건수,30877,35109,33606,33061,27165,23245,19590,...,10892,10683,11118,11318,10683,10249,9978,9896,7671,7075
4,서울시,차대사람,사망자수,0,0,0,0,0,0,0,...,235,215,214,211,196,189,182,139,113,120

서울시 구별 차량통행속도

  구분별(1) 구분별(2)  2013  2014  2015  2016  2017  2018  2019  2020  2021
0     전체     소계  26.4  25.7  25.2  24.2  24.2  23.9  23.8  24.1  23.0
1    권역별     강남  26.3  25.3  25.5  24.7  24.8  24.4  24.2  24.5  23.3
2    권역별     강북  25.3  24.6  24.8  23.7  23.7  23.4  23.3  23.8  22.7
3   자치구별    종로구  23.6  23.9  23.7  23.1  23.0  22.5  22.7  23.6  22.6
4   자치구별     중구  21.8  21.1  21.4  19.6  19.9  19.5  19.6  21.4  20.7

서울시 구별 인구밀도

,동별(1),동별(2),2007,2007.1,2007.2,2008,2008.1,2008.2,2009,2009.1,...,2018.2,2019,2019.1,2019.2,2020,2020.1,2020.2,2021,2021.1,2021.2
0,동별(1),동별(2),인구 (명),면적 (㎢),인구밀도 (명/㎢),인구 (명),면적 (㎢),인구밀도 (명/㎢),인구 (명),면적 (㎢),...,인구밀도 (명/㎢),인구 (명),면적 (㎢),인구밀도 (명/㎢),인구 (명),면적 (㎢),인구밀도 (명/㎢),인구 (명),면적 (㎢),인구밀도 (명/㎢)
1,합계,소계,10421782,605.25,17219,10456034,605.27,17275,10464051,605.25,...,16604,10010983,605.24,16541,9911088,605.23,16376,9736027,605.24,16086
2,합계,종로구,173843,23.91,7271,179754,23.91,7519,177543,23.91,...,6817,161869,23.91,6769,158996,23.91,6649,153789,23.91,6431
3,합계,중구,137435,9.96,13798,138811,9.96,13936,137861,9.96,...,13618,136488,9.96,13704,134635,9.96,13517,131787,9.96,13231
4,합계,용산구,248362,21.87,11358,251043,21.87,11480,251200,21.87,...,11209,245185,21.87,11213,244645,21.87,11188,237285,21.87,10852

In [3]:
df_acc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 318 entries, 0 to 317
Data columns (total 37 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   자치구     318 non-null    object
 1   사고유형    318 non-null    object
 2   구분      318 non-null    object
 3   1988    318 non-null    int64
 4   1989    318 non-null    int64
 5   1990    318 non-null    int64
 6   1991    318 non-null    int64
 7   1992    318 non-null    int64
 8   1993    318 non-null    int64
 9   1994    318 non-null    int64
 10  1995    318 non-null    int64
 11  1996    318 non-null    int64
 12  1997    318 non-null    int64
 13  1998    318 non-null    int64
 14  1999    318 non-null    int64
 15  2000    318 non-null    int64
 16  2001    318 non-null    int64
 17  2002    318 non-null    int64
 18  2003    318 non-null    int64
 19  2004    318 non-null    int64
 20  2005    318 non-null    int64
 21  2006    318 non-null    int64
 22  2007    318 non-null    int64
 23  2008    318 non-null    int64
 24  2009    318 non-null    int64
 25  2010    318 non-null    int64
 26  2011    318 non-null    int64
 27  2012    318 non-null    int64
 28  2013    318 non-null    int64
 29  2014    318 non-null    int64
 30  2015    318 non-null    int64
 31  2016    318 non-null    int64
 32  2017    318 non-null    int64
 33  2018    318 non-null    int64
 34  2019    318 non-null    int64
 35  2020    318 non-null    int64
 36  2021    318 non-null    int64
dtypes: int64(34), object(3)
memory usage: 92.1+ KB

In [4]:
df_speed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   구분별(1)  28 non-null     object
 1   구분별(2)  28 non-null     object
 2   2013    28 non-null     float64
 3   2014    28 non-null     float64
 4   2015    28 non-null     float64
 5   2016    28 non-null     float64
 6   2017    28 non-null     float64
 7   2018    28 non-null     float64
 8   2019    28 non-null     float64
 9   2020    28 non-null     float64
 10  2021    28 non-null     float64
dtypes: float64(9), object(2)
memory usage: 2.5+ KB

In [5]:
df_density.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 47 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   동별(1)   27 non-null     object
 1   동별(2)   27 non-null     object
 2   2007    27 non-null     object
 3   2007.1  27 non-null     object
 4   2007.2  27 non-null     object
 5   2008    27 non-null     object
 6   2008.1  27 non-null     object
 7   2008.2  27 non-null     object
 8   2009    27 non-null     object
 9   2009.1  27 non-null     object
 10  2009.2  27 non-null     object
 11  2010    27 non-null     object
 12  2010.1  27 non-null     object
 13  2010.2  27 non-null     object
 14  2011    27 non-null     object
 15  2011.1  27 non-null     object
 16  2011.2  27 non-null     object
 17  2012    27 non-null     object
 18  2012.1  27 non-null     object
 19  2012.2  27 non-null     object
 20  2013    27 non-null     object
 21  2013.1  27 non-null     object
 22  2013.2  27 non-null     object
 23  2014    27 non-null     object
 24  2014.1  27 non-null     object
 25  2014.2  27 non-null     object
 26  2015    27 non-null     object
 27  2015.1  27 non-null     object
 28  2015.2  27 non-null     object
 29  2016    27 non-null     object
 30  2016.1  27 non-null     object
 31  2016.2  27 non-null     object
 32  2017    27 non-null     object
 33  2017.1  27 non-null     object
 34  2017.2  27 non-null     object
 35  2018    27 non-null     object
 36  2018.1  27 non-null     object
 37  2018.2  27 non-null     object
 38  2019    27 non-null     object
 39  2019.1  27 non-null     object
 40  2019.2  27 non-null     object
 41  2020    27 non-null     object
 42  2020.1  27 non-null     object
 43  2020.2  27 non-null     object
 44  2021    27 non-null     object
 45  2021.1  27 non-null     object
 46  2021.2  27 non-null     object
dtypes: object(47)
memory usage: 10.0+ KB

In [6]:
df_acc.columns[:3]

Index(['자치구', '사고유형', '구분'], dtype='object')

In [7]:
# df_acc의 '1988' ~ '2012' 컬럼 삭제
columns = list(df_acc.columns[:3]) + [str(i) for i in range(2013, 2022)]

tmp_df = df_acc.copy()

tmp_df = tmp_df[columns]

df_acc = tmp_df.copy()
df_acc.head()

,자치구,사고유형,구분,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,서울시,합계,발생건수,39439,40792,41665,40039,38625,38795,39258,35227,33913
1,서울시,합계,사망자수,378,400,376,348,343,304,250,219,243
2,서울시,합계,부상자수,56761,57345,58656,55669,53810,53751,53904,47513,45223
3,서울시,차대사람,발생건수,10683,11118,11318,10683,10249,9978,9896,7671,7075
4,서울시,차대사람,사망자수,215,214,211,196,189,182,139,113,120

In [8]:
df_acc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 318 entries, 0 to 317
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   자치구     318 non-null    object
 1   사고유형    318 non-null    object
 2   구분      318 non-null    object
 3   2013    318 non-null    int64
 4   2014    318 non-null    int64
 5   2015    318 non-null    int64
 6   2016    318 non-null    int64
 7   2017    318 non-null    int64
 8   2018    318 non-null    int64
 9   2019    318 non-null    int64
 10  2020    318 non-null    int64
 11  2021    318 non-null    int64
dtypes: int64(9), object(3)
memory usage: 29.9+ KB

In [9]:
df_speed.head()

  구분별(1) 구분별(2)  2013  2014  2015  2016  2017  2018  2019  2020  2021
0     전체     소계  26.4  25.7  25.2  24.2  24.2  23.9  23.8  24.1  23.0
1    권역별     강남  26.3  25.3  25.5  24.7  24.8  24.4  24.2  24.5  23.3
2    권역별     강북  25.3  24.6  24.8  23.7  23.7  23.4  23.3  23.8  22.7
3   자치구별    종로구  23.6  23.9  23.7  23.1  23.0  22.5  22.7  23.6  22.6
4   자치구별     중구  21.8  21.1  21.4  19.6  19.9  19.5  19.6  21.4  20.7

In [ ]:
# df_speed 컬럼 수정
# '구분별(1)' 컬럼 삭제, '구분별(2)' -> '자치구'
# 또한 '자치구' 컬럼의 데이터 중 '강남', '강북' 데이터 제외
# '자치구' 컬럼의 데이터 중 '소계' 데이터 '서울시'로 변경
# '구분' 컬럼 추가 후 해당 컬럼에 '차량통행속도' 데이터 저장
ordered_columns = ['자치구', '구분'] + [str(i) for i in range(2013, 2022)]

tmp_df = df_speed.copy()

tmp_df = tmp_df[list(tmp_df.columns[1:])]
tmp_df = tmp_df.rename(columns={tmp_df.columns[0]: '자치구'})

tmp_df.loc[tmp_df['자치구'] == '소계', '자치구'] = '서울시'
tmp_df = tmp_df[~tmp_df['자치구'].isin(['강남', '강북'])]

tmp_df['구분'] = '차량통행속도'
tmp_df = tmp_df[ordered_columns]
tmp_df = tmp_df.reset_index(drop=True)

df_speed = tmp_df.copy()
df_speed.head()

   자치구      구분  2013  2014  2015  2016  2017  2018  2019  2020  2021
0  서울시  차량통행속도  26.4  25.7  25.2  24.2  24.2  23.9  23.8  24.1  23.0
1  종로구  차량통행속도  23.6  23.9  23.7  23.1  23.0  22.5  22.7  23.6  22.6
2   중구  차량통행속도  21.8  21.1  21.4  19.6  19.9  19.5  19.6  21.4  20.7
3  용산구  차량통행속도  28.6  28.5  28.9  26.8  27.0  26.6  26.5  27.1  26.1
4  성동구  차량통행속도  27.7  27.9  28.1  25.5  25.5  25.0  24.9  25.4  23.8

In [11]:
df_density['동별(1)'].unique()

array(['동별(1)', '합계'], dtype=object)

In [ ]:
# df_density 컬럼 및 데이터 수정
# '동별(2)' 컬럼명 '자치구'로 수정
# '자치구' 컬럼의 데이터 중 '소계' 데이터 '서울시'로 수정
# '동별(1)' 컬럼 삭제
# 컬럼 이름에 '.1', '.2'가 포함되어 있다면 삭제 (ex. '2022.2' -> '2022')
# '구분' 컬럼 생성 후 해당 컬럼에 '인구', '면적', '인구밀도' 데이터 저장
# '구분' 컬럼의 데이터에 맞게 '2013' ~ '2021' 컬럼 데이터 채우기 
columns = ['자치구', '구분'] + [str(i) for i in range(2013, 2022)]

tmp_df = df_density.copy()

tmp_df = tmp_df[tmp_df.columns[1:]]
tmp_df = tmp_df.rename(columns={tmp_df.columns[0]: '자치구'})
tmp_df.loc[tmp_df['자치구'] == '소계', '자치구'] = '서울시'
tmp_df = tmp_df.drop(index=0)
tmp_df.columns = tmp_df.columns.str.replace(r'\.1|\.2', '', regex=True)

tmp_df = tmp_df.melt(id_vars=['자치구'], var_name='년도', value_name='값')
tmp_df['구분'] = tmp_df.groupby(['자치구', '년도']).cumcount().map({0:'인구', 1:'면적', 2:'인구밀도'})
tmp_df = tmp_df.pivot_table(
    index=['자치구', '구분'],
    columns='년도',
    values='값',
    aggfunc='first',
    sort=False
).reset_index()

tmp_df.columns.name = None
tmp_df = tmp_df[columns]
for col in columns[2:]:
    tmp_df[col] = tmp_df[col].astype(float)

df_density = tmp_df.copy()
df_density.head()

,자치구,구분,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,서울시,인구,10388055.00,10369593.00,10297138.00,10204057.00,10124579.00,10049607.00,10010983.00,9911088.00,9736027.00
1,서울시,면적,605.20,605.21,605.25,605.20,605.24,605.24,605.24,605.23,605.24
2,서울시,인구밀도,17165.00,17134.00,17013.00,16861.00,16728.00,16604.00,16541.00,16376.00,16086.00
3,종로구,인구,167867.00,165344.00,163822.00,161922.00,164257.00,163026.00,161869.00,158996.00,153789.00
4,종로구,면적,23.91,23.91,23.91,23.91,23.91,23.91,23.91,23.91,23.91

In [13]:
# 처리한 df_acc, df_speed, df_density 합치기
gu_list = ['서울시', '종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구', '강북구', '도봉구', '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구', '금천구', '영등포구', '동작구', '관악구', '서초구', '강남구', '송파구', '강동구']
cat_list = ['발생건수', '사망자수', '부상자수', '차량통행속도', '인구', '면적', '인구밀도']
type_list = ['합계', '차대사람', '차대차', '차량단독', '건널목', '-']

tmp_df = pd.concat([df_acc, df_speed, df_density], axis=0, ignore_index=True)
tmp_df.loc[tmp_df['구분'].isin(['차량통행속도', '인구', '면적', '인구밀도']) &
           tmp_df['사고유형'].isna(), '사고유형'] = '-'

tmp_df['자치구'] = pd.Categorical(tmp_df['자치구'], categories=gu_list, ordered=True)
tmp_df['구분'] = pd.Categorical(tmp_df['구분'], categories=cat_list, ordered=True)
tmp_df['사고유형'] = pd.Categorical(tmp_df['사고유형'], categories=type_list, ordered=True)
tmp_df = tmp_df.sort_values(['자치구', '사고유형', '구분']).reset_index(drop=True)

df_target = tmp_df.copy()
df_target.head(20)

,자치구,사고유형,구분,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,서울시,합계,발생건수,39439.0,40792.00,41665.00,40039.0,38625.00,38795.00,39258.00,35227.00,33913.00
1,서울시,합계,사망자수,378.0,400.00,376.00,348.0,343.00,304.00,250.00,219.00,243.00
2,서울시,합계,부상자수,56761.0,57345.00,58656.00,55669.0,53810.00,53751.00,53904.00,47513.00,45223.00
3,서울시,차대사람,발생건수,10683.0,11118.00,11318.00,10683.0,10249.00,9978.00,9896.00,7671.00,7075.00
4,서울시,차대사람,사망자수,215.0,214.00,211.00,196.0,189.00,182.00,139.00,113.00,120.00
5,서울시,차대사람,부상자수,11159.0,11621.00,11831.00,11144.0,10706.00,10402.00,10320.00,7996.00,7332.00
6,서울시,차대차,발생건수,27358.0,28201.00,28854.00,28030.0,27103.00,27522.00,28150.00,26508.00,25926.00
7,서울시,차대차,사망자수,121.0,150.00,116.00,120.0,117.00,96.00,84.00,80.00,92.00
8,서울시,차대차,부상자수,43928.0,44016.00,45086.00,42936.0,41642.00,41889.00,42181.00,38373.00,36909.00
9,서울시,차량단독,발생건수,1398.0,1473.00,1493.00,1326.0,1273.00,1295.00,1212.00,1048.00,912.00
10,서울시,차량단독,사망자수,42.0,36.00,49.00,32.0,37.00,26.00,27.00,26.00,31.00
11,서울시,차량단독,부상자수,1674.0,1708.00,1739.00,1589.0,1462.00,1460.00,1403.00,1144.00,982.00
12,서울시,건널목,발생건수,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00
13,서울시,건널목,부상자수,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00
14,서울시,-,차량통행속도,26.4,25.70,25.20,24.2,24.20,23.90,23.80,24.10,23.00
15,서울시,-,인구,10388055.0,10369593.00,10297138.00,10204057.0,10124579.00,10049607.00,10010983.00,9911088.00,9736027.00
16,서울시,-,면적,605.2,605.21,605.25,605.2,605.24,605.24,605.24,605.23,605.24
17,서울시,-,인구밀도,17165.0,17134.00,17013.00,16861.0,16728.00,16604.00,16541.00,16376.00,16086.00
18,종로구,합계,발생건수,1274.0,1314.00,1414.00,1299.0,1190.00,1134.00,1133.00,903.00,778.00
19,종로구,합계,사망자수,13.0,11.00,8.00,9.0,13.00,6.00,6.00,5.00,6.00

In [ ]:
# 종로구의 cat_list 구하기 
cat_list = ['인구 만명당 발생건수', '인구 만명당 사망자수', '인구 만명당 부상자수',
            '인구밀도당 부상자수', '인구밀도당 사망자수', '인구밀도당 발생건수',
            '차량통행속도당 사망자수', '차량통행속도당 발생건수', '차량통행속도당 부상자수']
type_list = ['합계', '차대사람', '차대차', '차량단독']
columns = [str(i) for i in range(2013, 2022)]
target_columns = ['발생건수', '사망자수', '부상자수']

jongno_df = df_target[df_target['자치구'] == '종로구'].copy()

population = jongno_df[jongno_df['구분'] == '인구'][columns].values[0]
density = jongno_df[jongno_df['구분'] == '인구밀도'][columns].values[0]
speed = jongno_df[jongno_df['구분'] == '차량통행속도'][columns].values[0]

population_df = jongno_df[jongno_df['구분'].isin(target_columns)].copy()
population_df['구분'] = '인구 만명당 ' + population_df['구분'].astype(str)
population_df[columns] = population_df[columns].div(population / 10000, axis=1).round(2)

density_df = jongno_df[jongno_df['구분'].isin(target_columns)].copy()
density_df['구분'] = '인구밀도당 ' + density_df['구분'].astype(str)
density_df[columns] = (density_df[columns].values / density).round(2)

speed_df = jongno_df[jongno_df['구분'].isin(target_columns)].copy()
speed_df['구분'] = '차량통행속도당 ' + speed_df['구분'].astype(str)
speed_df[columns] = (speed_df[columns].values / speed).round(2)

df_result = pd.concat([population_df, density_df, speed_df], axis=0)

df_result['사고유형'] = pd.Categorical(df_result['사고유형'], categories=type_list, ordered=True)
df_result['구분'] = pd.Categorical(df_result['구분'], categories=cat_list, ordered=True)
df_result = df_result.sort_values(['사고유형', '구분']).reset_index(drop=True)

df_result.head(10)

,자치구,사고유형,구분,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,종로구,합계,인구 만명당 발생건수,75.89,79.47,86.31,80.22,72.45,69.56,69.99,56.79,50.59
1,종로구,합계,인구 만명당 사망자수,0.77,0.67,0.49,0.56,0.79,0.37,0.37,0.31,0.39
2,종로구,합계,인구 만명당 부상자수,105.44,108.26,117.99,107.95,102.83,94.83,96.31,76.98,68.28
3,종로구,합계,인구밀도당 부상자수,0.25,0.26,0.28,0.26,0.25,0.23,0.23,0.18,0.16
4,종로구,합계,인구밀도당 사망자수,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
5,종로구,합계,인구밀도당 발생건수,0.18,0.19,0.21,0.19,0.17,0.17,0.17,0.14,0.12
6,종로구,합계,차량통행속도당 사망자수,0.55,0.46,0.34,0.39,0.57,0.27,0.26,0.21,0.27
7,종로구,합계,차량통행속도당 발생건수,53.98,54.98,59.66,56.23,51.74,50.40,49.91,38.26,34.42
8,종로구,합계,차량통행속도당 부상자수,75.00,74.90,81.56,75.67,73.43,68.71,68.68,51.86,46.46
9,종로구,차대사람,인구 만명당 발생건수,21.68,23.35,24.11,24.27,20.27,20.61,18.84,14.03,11.83

In [16]:
# 서울시 포함 전체 자치구의 cat_list 구하기
gu_list = ['서울시', '종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구', '강북구', '도봉구', '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구', '금천구', '영등포구', '동작구', '관악구', '서초구', '강남구', '송파구', '강동구']
cat_list = ['인구 만명당 발생건수', '인구 만명당 사망자수', '인구 만명당 부상자수', '인구밀도당 발생건수', '인구밀도당 사망자수', '인구밀도당 부상자수',  '차량통행속도당 발생건수', '차량통행속도당 사망자수',  '차량통행속도당 부상자수']
type_list = ['합계', '차대사람', '차대차', '차량단독', '건널목']
columns = [str(i) for i in range(2013, 2022)]
target_columns = ['발생건수', '사망자수', '부상자수']

result_list = []
for gu in gu_list:
    tmp_df = df_target[df_target['자치구'] == gu].copy()
    
    population = tmp_df[tmp_df['구분']=='인구'][columns].values[0]
    density = tmp_df[tmp_df['구분']=='인구밀도'][columns].values[0]
    speed = tmp_df[tmp_df['구분']=='차량통행속도'][columns].values[0]
    
    population_df = tmp_df[tmp_df['구분'].isin(target_columns)].copy()
    population_df['구분'] = '인구 만명당 ' + population_df['구분'].astype(str)
    population_df[columns] = population_df[columns].div(population/10000, axis=1).round(2)
    result_list.append(population_df)
    
    density_df = tmp_df[tmp_df['구분'].isin(target_columns)].copy()
    density_df['구분'] = '인구밀도당 ' + density_df['구분'].astype(str)
    density_df[columns] = (density_df[columns].values / density).round(2)
    result_list.append(density_df)
    
    speed_df = tmp_df[tmp_df['구분'].isin(target_columns)].copy()
    speed_df['구분'] = '차량통행속도당 ' + speed_df['구분'].astype(str)
    speed_df[columns] = (speed_df[columns].values / speed).round(2)
    result_list.append(speed_df)

df_result = pd.concat(result_list, axis=0)

df_result['자치구'] = pd.Categorical(df_result['자치구'], categories=gu_list, ordered=True)
df_result['사고유형'] = pd.Categorical(df_result['사고유형'], categories=type_list, ordered=True)
df_result['구분'] = pd.Categorical(df_result['구분'], categories=cat_list, ordered=True)
df_result = df_result.sort_values(['자치구','사고유형','구분']).reset_index(drop=True)

df_result.head(10)

,자치구,사고유형,구분,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,서울시,합계,인구 만명당 발생건수,37.97,39.34,40.46,39.24,38.15,38.60,39.21,35.54,34.83
1,서울시,합계,인구 만명당 사망자수,0.36,0.39,0.37,0.34,0.34,0.30,0.25,0.22,0.25
2,서울시,합계,인구 만명당 부상자수,54.64,55.30,56.96,54.56,53.15,53.49,53.84,47.94,46.45
3,서울시,합계,인구밀도당 발생건수,2.30,2.38,2.45,2.37,2.31,2.34,2.37,2.15,2.11
4,서울시,합계,인구밀도당 사망자수,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.01,0.02
5,서울시,합계,인구밀도당 부상자수,3.31,3.35,3.45,3.30,3.22,3.24,3.26,2.90,2.81
6,서울시,합계,차량통행속도당 발생건수,1493.90,1587.24,1653.37,1654.50,1596.07,1623.22,1649.50,1461.70,1474.48
7,서울시,합계,차량통행속도당 사망자수,14.32,15.56,14.92,14.38,14.17,12.72,10.50,9.09,10.57
8,서울시,합계,차량통행속도당 부상자수,2150.04,2231.32,2327.62,2300.37,2223.55,2249.00,2264.87,1971.49,1966.22
9,서울시,차대사람,인구 만명당 발생건수,10.28,10.72,10.99,10.47,10.12,9.93,9.89,7.74,7.27

In [17]:
# '사고유형' 컬럼이 '합계'인 데이터 중 각 '구분'별 및 '연도'별 
# 값이 최대인 서울시 포함 자치구 구하기
columns = ['사고유형', '구분', '연도', '자치구', '값']
cat_list = ['인구 만명당 발생건수', '인구밀도당 발생건수', '차량통행속도당 발생건수']
years = [str(i) for i in range(2013, 2022)]

total_df = df_result[(df_result['사고유형'] == '합계') &
                     (df_result['자치구'] != '서울시')]
total_df = total_df[total_df['구분'].isin(cat_list)]

total_df = total_df.melt(id_vars=['사고유형', '자치구', '구분'],
                         value_vars=years,
                         var_name='연도',
                         value_name='값')

idx = total_df.groupby(['구분', '연도'], observed=True)['값'].idxmax()

total_df = total_df.loc[idx, columns]

total_df = total_df.sort_values(['구분', '연도']).reset_index(drop=True)

df_answer = total_df.copy()
df_answer

   사고유형            구분    연도  자치구       값
0    합계   인구 만명당 발생건수  2013   중구  104.50
1    합계   인구 만명당 발생건수  2014   중구   95.80
2    합계   인구 만명당 발생건수  2015   중구   99.61
3    합계   인구 만명당 발생건수  2016   중구   95.83
4    합계   인구 만명당 발생건수  2017   중구   93.02
5    합계   인구 만명당 발생건수  2018   중구   83.17
6    합계   인구 만명당 발생건수  2019   중구   86.75
7    합계   인구 만명당 발생건수  2020   중구   70.93
8    합계   인구 만명당 발생건수  2021  강남구   71.03
9    합계    인구밀도당 발생건수  2013  강남구    0.25
10   합계    인구밀도당 발생건수  2014  강남구    0.25
11   합계    인구밀도당 발생건수  2015  강남구    0.27
12   합계    인구밀도당 발생건수  2016  강남구    0.26
13   합계    인구밀도당 발생건수  2017  서초구    0.25
14   합계    인구밀도당 발생건수  2018  서초구    0.27
15   합계    인구밀도당 발생건수  2019  강남구    0.27
16   합계    인구밀도당 발생건수  2020  강남구    0.27
17   합계    인구밀도당 발생건수  2021  강동구    5.54
18   합계  차량통행속도당 발생건수  2013  강남구  147.95
19   합계  차량통행속도당 발생건수  2014  강남구  156.21
20   합계  차량통행속도당 발생건수  2015  강남구  169.66
21   합계  차량통행속도당 발생건수  2016  강남구  153.12
22   합계  차량통행속도당 발생건수  2017  강남구  139.88
23   합계  차량통행속도당 발생건수  2018  강남구  141.18
24   합계  차량통행속도당 발생건수  2019  강남구  152.54
25   합계  차량통행속도당 발생건수  2020  강남구  150.08
26   합계  차량통행속도당 발생건수  2021  강남구  161.18